### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by violetavivi**

### CODE REVIEW

**Comment by TLouf** [comment]
Seeing you added Manlio's newsletter, it got me thinking it would probably make sense to have a newsletters/mailing lists section, what do you think? The Complexity Digest would fit better in there, and there are others to add (SOCNET comes off the top of my head).

**Comment by violetavivi** [comment]
That's a good idea! Other newsletters that come to my mind are the CSS , NetSci and SFI newsletters

**Comment by TLouf** [comment]
I've just pushed the new section to the list, feel free to add Complexity Thoughts in there and whatever else you have in mind, either in this PR or a new one, as you prefer.

**Comment by violetavivi** [comment]
done ;)

**Comment by TLouf** [comment]
Great, thanks a lot for the contribution :)

**Pull request merged**
